class PurokList {
  List<String> purokList = [
    'Purok New San Isidro',
    'Purok Old San Isidro',
    'Purok Medalla Melagrosa',
    'Purok San Nicolas',
    'PurokSan Lorenzo',
    'Purok Waling-waling',
    'Purok Orchids',
    'Purok Purok Pine Tree',
    'Purok Upper St. Jude',
    'Purok Lower St Jude',
    'Purok Damayan',
    'Purok Molave',
    'Purok Sta. Cruz',
    'Purok Balite 1 and 2',
    'Purok Buhangin Hills',
    'Purok Panorama Village',
    'Purok Engan Village',
    'Purok Pioneer Village',
    'Purok Lopzcom',
    'Purok Spring Valley 1 and 2',
    'Purok Maglana',
    'Purok Sandawa',
    'Purok NIC',
    'Purok Watusi',
    'Purok Palm Drive',
    'Purok Sto. Rosario',
    'Purok Sampaguita',
    'Purok San Pedro Village',
    'Ladislawa Village',
    'Purok Bagong Lipunan',
    'Nccc Village',
    'Purok Sta. Maria',
    'Purok San Miguel Lower and Upper',
    'Purok Dumanlas Proper',
    'Purok Birsaba',
    'Purok Sto. Niño',
    'Purok Anahaw',
    'Purok Mt. Carmel',
    'Purok Talisay',
    'Purok Sta. Teresita',
    'Purok Mahayag',
    'Purok San Vicente',
    'Purok San Antonio',
    'NHA Buhangin',
    'Purok Lourdes',
    'Purok San Jose',
    'Pirok Blk. 2',
    'Purok Blk. 10',
    'Hillside Sibdivision',
    'Purok Kalayaan',
    'Purok Margarita',
    'Purok Cubcub',
    'Bread Village',
    'Purok Apollo',
    'Carnation St.',
    'Purok Sunflower',
  ];
}
